/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/verbs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all verbs */
        get: {
            parameters: {
                query?: {
                    ids?: string;
                    isFavorite?: boolean;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of verbs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Verb"][];
                    };
                };
                400: components["responses"]["BadRequestError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verbs/{verbId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a verb by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    verbId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A verb */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Verb"];
                    };
                };
                400: components["responses"]["BadRequestError"];
                404: components["responses"]["NotFoundError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Verb: {
            /** @example 1 */
            id: string;
            /** @example gehen */
            infinitive: string;
            /** @example ging */
            past: string;
            /** @example gegangen */
            participle: string;
            /** @example to go */
            translation: string;
            /** @example false */
            isFavorite: boolean;
            /** @example ei – ie – ie */
            group: string;
        };
        Error: {
            message: string;
            code: string;
        };
    };
    responses: {
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Bad request */
        BadRequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
