openapi: 3.0.0
info:
  title: German Irregular Verbs API
  description: API for learning German irregular verbs
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /verbs:
    get:
      summary: Get all verbs
      parameters:
        - name: ids
          in: query
          required: false
          schema:
            type: string
        - name: isFavorite
          in: query
          required: false
          schema:
            type: boolean
        - name: search
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: List of verbs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Verb"
        "400":
          $ref: "#/components/responses/BadRequestError"

  /verbs/{verbId}:
    get:
      summary: Get a verb by ID
      parameters:
        - in: path
          name: verbId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A verb
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Verb"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "400":
          $ref: "#/components/responses/BadRequestError"

components:
  schemas:
    Verb:
      type: object
      required:
        - id
        - infinitive
        - past
        - participle
        - translation
        - isFavorite
        - group
      properties:
        id:
          type: string
          example: "1"
        infinitive:
          type: string
          example: "gehen"
        past:
          type: string
          example: "ging"
        participle:
          type: string
          example: "gegangen"
        translation:
          type: string
          example: "to go"
        isFavorite:
          type: boolean
          example: false
        group:
          type: string
          example: "ei – ie – ie"

    Error:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: string

  responses:
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

    BadRequestError:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
