import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema/generated"; // generated by openapi-typescript
import { CONFIG } from "@/app/config/config";

export const fetchClient = createFetchClient<paths>({
  baseUrl: `${CONFIG.API_BASE_URL}/api`,
});

export const rqClient = createClient(fetchClient);
